//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLGranite.Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Slabs = new HashSet<Slab>();
            this.Tombs = new HashSet<Tomb>();
        }
    
        public int Id { get; set; }
        public string Reference { get; set; }
        public int SoldToId { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Slab> Slabs { get; set; }
        public virtual ICollection<Tomb> Tombs { get; set; }
    }
}
