//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLGranite.Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockType
    {
        public StockType()
        {
            this.Activities = new HashSet<Activity>();
            this.Statuses = new HashSet<Status>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public short Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Status> Statuses { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
