//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLGranite.Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tomb
    {
        public int Id { get; set; }
        public int StockId { get; set; }
        public int SoldToId { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual User SoldTo { get; set; }
    }
}
