//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLGranite.Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Active = true;
            this.Activities = new HashSet<Activity>();
            this.Nisans = new HashSet<Nisan>();
            this.Nisans1 = new HashSet<Nisan>();
            this.Projects = new HashSet<Project>();
            this.Slabs = new HashSet<Slab>();
            this.Slabs1 = new HashSet<Slab>();
            this.Tombs = new HashSet<Tomb>();
        }
    
        public int Id { get; set; }
        public short UserTypeId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Remarks { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Nisan> Nisans { get; set; }
        public virtual ICollection<Nisan> Nisans1 { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Slab> Slabs { get; set; }
        public virtual ICollection<Slab> Slabs1 { get; set; }
        public virtual ICollection<Tomb> Tombs { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
